name: Deploy Frontend

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build & Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installation Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Installation des dépendances
        run: npm install

      - name: Build de production
        run: npm run build

      - name: Déploiement sur le VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: bash /var/www/frontend/scripts/deploy.sh
